// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxnnWd_xI-whfz8na2ug8n0DDYjcsp0kk',
    appId: '1:466566112835:web:a8629a22617ca0342056f6',
    messagingSenderId: '466566112835',
    projectId: 'pengenalanprofesi',
    authDomain: 'pengenalanprofesi.firebaseapp.com',
    databaseURL: 'https://pengenalanprofesi-default-rtdb.firebaseio.com',
    storageBucket: 'pengenalanprofesi.firebasestorage.app',
    measurementId: 'G-6VTLYWB1VD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9jSJ1xa9AVR8ZSdZ_p-iOfVF17eJG3qs',
    appId: '1:466566112835:android:77303825e92e41502056f6',
    messagingSenderId: '466566112835',
    projectId: 'pengenalanprofesi',
    databaseURL: 'https://pengenalanprofesi-default-rtdb.firebaseio.com',
    storageBucket: 'pengenalanprofesi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfgOJTYCUlFYhAcjyluDziDXwQ6orj-8M',
    appId: '1:466566112835:ios:8551dc10daa566332056f6',
    messagingSenderId: '466566112835',
    projectId: 'pengenalanprofesi',
    databaseURL: 'https://pengenalanprofesi-default-rtdb.firebaseio.com',
    storageBucket: 'pengenalanprofesi.firebasestorage.app',
    iosBundleId: 'com.example.pengenalanprofesi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfgOJTYCUlFYhAcjyluDziDXwQ6orj-8M',
    appId: '1:466566112835:ios:8551dc10daa566332056f6',
    messagingSenderId: '466566112835',
    projectId: 'pengenalanprofesi',
    databaseURL: 'https://pengenalanprofesi-default-rtdb.firebaseio.com',
    storageBucket: 'pengenalanprofesi.firebasestorage.app',
    iosBundleId: 'com.example.pengenalanprofesi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxnnWd_xI-whfz8na2ug8n0DDYjcsp0kk',
    appId: '1:466566112835:web:87caed83bb964bad2056f6',
    messagingSenderId: '466566112835',
    projectId: 'pengenalanprofesi',
    authDomain: 'pengenalanprofesi.firebaseapp.com',
    databaseURL: 'https://pengenalanprofesi-default-rtdb.firebaseio.com',
    storageBucket: 'pengenalanprofesi.firebasestorage.app',
    measurementId: 'G-9KM799REJY',
  );
}
